### PR TITLE
Write can be called multiple times, so adding a way to prevent writing headers

### PR DESCRIPTION
**Pull request by jvelasques**
For example, you can be chunk reading documents from an Elastic Search cluster, and writing as you process them.

### CODE REVIEW

**Comment by jvelasques** [comment]
Hi there!

I was actually reluctant to do that just because it changes the flow. Not sure who'd want to write headers in the middle of the file though, so the change does make sense. I'll change this PR!

Thanks!

**Comment by joaomatossilva** [comment]
> Not sure who'd want to write headers in the middle of the file

Yup. My point exactly.

**Comment by jvelasques** [comment]
@joaomatossilva changed! Hopefully the test makes sense 😅 

Thanks!

**Comment by diogogcunha** [comment]
Just as a nice extra info on this conversation, we were able to use this to stream an Elastic Search paged result into a CSV file directly on Azure Blob never storing anything on the local file system. 
It worked really nicely! Congrats on this project

**Comment by joaomatossilva** [comment]
I've fixed (or so I think) the version tag on master. If you could rebase your change on top of it would be great.

Call me on Whatzapp if you need help doing it ;)

**Pull request merged**
